### ISSUE TITLE
Issue when writing in an EditText that appears in another page of a ViewPager

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#107]
Same than #68 , but writing into `EditText`. That's strange... looked at the source, and it should work. It's EDD time.

Just for the information, a piece of code to showcase the issue. The click works and the write not:

```java
click(R.id.et_postal_code)
writeToEditText(R.id.et_postal_code, "17750")
```

**Comment by Sloy** [comment]
This is supposed to be fixed after https://github.com/SchibstedSpain/Barista/pull/198
If you find anything any other issue reopen it @rocboronat :D
