### ISSUE TITLE
PermissionGranter doesn't select the correct object (clicks on refuse)

### ISSUE THREAD

**Issue by crgarridos** [SchibstedSpain/Barista#108]
I'm working on a Lenovo TB3-850M and a Moto G2 2014 and instead of accepting the permission, it refuse it LOL

If I set the index to 2 it works fine. Anyway I don't know if other people had the problem before. 

Another way to make it work is using: 
`new UiSelector().clickable(true).checkable(false).resourceId("com.android.packageinstaller:id/permission_allow_button")`

Thanks

**Comment by rocboronat** [comment]
Big LOL! One question @crgarridos, what Android version are you running? As the permission dialog is part of the OS, i suspect that the issue is related to the Android version. Thanks!

**Comment by crgarridos** [comment]
6.0 in both, I didn't try in other devices.
I know, is too weird... I looked a lot for anyone having the same issue, but nobody had it.
anyway, could be better selecting the object with the ID ?

**Comment by crgarridos** [comment]
I was suspecting about the device language (French in my case), not related neither.

**Comment by rocboronat** [comment]
@crgarridos the thing is that, as we click on the button via UIAutomator, we can't access to the ID. But feel free to check it again... we did on year ago and we were not proficient with UIAutomator, whoops :·)

**Comment by rocboronat** [comment]
Fixed at #110 by the creator of this issue, @crgarridos! Big thanks! 🎉
