### ISSUE TITLE
Avoid calling the FailureHandler for expected errors

### ISSUE THREAD

**Issue by Sloy** [SchibstedSpain/Barista#116]
Barista does lots of magic tricks and we love that. But one of those tricks is to rely on `try/catch` patterns to allow higher level tests.

This has one big drawback: Espresso's [FailureHandler](https://developer.android.com/reference/android/support/test/espresso/FailureHandler.html) get's invoked every time, **even when the thrown exception is catched and ignored**.

Usually it's not a big deal, but when using custom FailureHandlers to do things like taking a screenshot when a test fails, it becomes a real pain. You can't tell when there was an actual error and when it's just a "ghost error" from Barista.

## Proposal
My proposal is to use the `withFailureHandler()` method on all Barista "magic" methods to override the global FailureHandler and avoid invoking it.

```java
try {
      onView(withId(id))
          .withFailureHandler(baristaFailureHandler)
          .check(matches(isDisplayed()));
    } catch (AssertionFailedError | PerformException e) {
      ...
    }
```

## Discussion
But there's something I'm not sure about. From the test perspective, what should happen when a 3-attempts test fails? The global FailureHandler should be notified somehow (to take the screenshot, for example). But it takes two parameters, a `Throwable` and a `Matcher<View>`. Since Barista usually tries with multiple matchers, which one should we use? Any of them? The simplest one? A fake one? 

I would love to hear some opinions, and see if we can find a good solution.

**Comment by rocboronat** [comment]
Thanks for asking @Sloy! I wrote a huge comment about my opinion, some pros and cons... but now I'm replacing it with a great "don't know". Sorry! 😅

My opinion was related with, being a Barista's user, and knowing that there are dragons inside Barista, just doing the simpler solution for us will do the work.

**Comment by CristianGM** [comment]
I could even say something "horrible", store the las error on `baristaFailureHandler` and use those stored values when calling the global FailureHandler.

I means we trust we won't have concurrency issues. I don't like the solution, but seems a "good" solution.

**Comment by Sloy** [comment]
@CristianGM we could use a new instance of the handler for each method so concurrency wouldn't be an issue. 

If we pass the latest error, the problem still would be that we might be showing a misleading error. But I'm not sure how horrible would that be, if any. 

I'm going to try it and see what happens.

**Comment by Sloy** [comment]
Done!
