### ISSUE TITLE
Remove NestedEnabledScrollToAction

### ISSUE THREAD

**Issue by CristianGM** [SchibstedSpain/Barista#117]
We are using Espresso 3.0 now so we can take advantage of it:
from the [changelog](https://developer.android.com/topic/libraries/testing-support-library/release-notes.html)
> Enhanced scrollTo() view action to work with descendants of ListView

it means reverting #96

**Comment by alorma** [comment]
Descendants of ListView.... it includes NestedScrollView?

**Comment by rocboronat** [comment]
@CristianGM there's a question by @alorma :·D

**Comment by Sloy** [comment]
@CristianGM there's a question by @alorma :·D

**Comment by Sloy** [comment]
From the code it doesn't look like it works with NestedScrollView yet.

```java
public Matcher<View> getConstraints() {
    return allOf(
        withEffectiveVisibility(Visibility.VISIBLE),
        isDescendantOfA(
            anyOf(
                isAssignableFrom(ScrollView.class),
                isAssignableFrom(HorizontalScrollView.class),
                isAssignableFrom(ListView.class))));
  }
```

**Comment by Sloy** [comment]
I'm gonna close this. If you find something different @CristianGM reopen it please.
