### ISSUE TITLE
Disable unwanted PR merging options

### ISSUE THREAD

**Issue by Sloy** [SchibstedSpain/Barista#12]
By default the three merging options are enabled (merge, squash&merge, rebase&merge).
We should always merge PRs the same way, so leaving only the prefered option could avoid mistakes.

We've been using the squash&merge option, so we should disable the other two.

**Comment by rocboronat** [comment]
Wep @Sloy ! If it takes less than doing it than opening an issue... just do it :·P

By the way, done! Thanks for spotting!

**Comment by Sloy** [comment]
@rocboronat I know. But I don't have permissions 😂

**Comment by Sloy** [comment]
Thanks!

**Comment by rocboronat** [comment]
My bad! Fix'd! ❤️
