### ISSUE TITLE
assertText(R.id.widget, "expected text")

### ISSUE THREAD

**Issue by estefafdez** [SchibstedSpain/Barista#120]
There is no way to get the text on a textView and compare with a string parameter to check if the text is the same or not.

**Comment by rocboronat** [comment]
That's not the way to use Espresso nor Barista. Instead of getting the text of the `TextView`, just use Barista's `assertDisplayed(yourExpectedText)`

**Comment by rocboronat** [comment]
Hello @estefafdez! Does my answer solve the question?

**Comment by estefafdez** [comment]
Hello, yes, but if I want to get the text from the textView because the text was modified on different activities, is there any way to get it? Only with the assertDisplayed?

**Comment by rocboronat** [comment]
Yes, the idea is that Espresso doesn't encourage us to get the data from a widget. So, the Espresso way to check that this text is being shown is to use the `assertDisplayed(something)` method.

If you need to check that a given text is shown in a given `TextView`, we could write a `assertText(R.id.widget, "expected text")` method, but if you can go on with the simple `assertDisplayed()` one... :·D

**Comment by estefafdez** [comment]
The assertText method sounds great, I think it could be helpful for people like me, used to work with tools such as Appium or Selenium on Automation Testing. Thank you!

**Comment by rocboronat** [comment]
Ok! Let me add to the backlog :·)

**Comment by estefafdez** [comment]
Perfect, thanks, a lot!

**Comment by EsteveAguilera** [comment]
This issue can be closed, it was fixed with the merge of #165!
