### ISSUE TITLE
Strings with parameters

### ISSUE THREAD

**Issue by alorma** [SchibstedSpain/Barista#122]
Hi Baristas!

Today i was in the situation where i needed to check for string to be displayed, but this (from resources) needs a param, like that:

```
<string name="empty_state_message">You have no %1$s messages</string>
```

And then, on test:

```
String noBroadcastText = targetContext.getString(R.string.empty_state_message, "broadcast");
assertDisplayed(noBroadcastText);
```

What do you think about creating a simplier method:

```
assertDisplayed(R.string.empty_state_message, "broadcast");
```

So, it will automatic build the string, and checks for it?

**Comment by alorma** [comment]
(I can add it myself)

**Comment by estefafdez** [comment]
Hello @alorma 
I opened an issue with a similar situation of what you describes: https://github.com/SchibstedSpain/Barista/issues/120

**Comment by rocboronat** [comment]
For me, that's not the focus of Barista... I mean, this is not a problem related with Espresso, UIAutomator, the flakiness of the tests... it adds complexity to Barista to solve an issue not related to the test framework itself.

Let's see the opinion of @Sloy and @SmasSive :·)

**Comment by Sloy** [comment]
Agree, I think that having a shortcut method for formatting strings is too much specific. Specially since `assertDisplayed()` is not intended only for strings, but also for views in general.

**Comment by SmasSive** [comment]
Agreed as well, this would be just a wrapper that will give us more problems than benefits (what about errors? What about to trace them? How we should handle them?) too much questions... 
And finally as Roc and Rafa say, this is not the intention of the library.

**Comment by alorma** [comment]
Ok!

**Comment by rocboronat** [comment]
Thanks for the good vibes @alorma 🌮
