### ISSUE TITLE
Make BitmapComparator internal

### ISSUE THREAD

**Issue by SmasSive** [SchibstedSpain/Barista#124]
`BitmapComparator.kt` should be internal but currently we cannot make it because there is a bug in kotlin plugin that should be fixed on the next 1.1.5 version.
Follow up here: https://discuss.kotlinlang.org/t/idea-cannot-access-internal-methods-from-tests/3832

**Comment by Sloy** [comment]
Related: https://github.com/SchibstedSpain/Barista/issues/86

**Comment by Sloy** [comment]
Could you take a new look at this @SmasSive? Is it possible now?

**Comment by EsteveAguilera** [comment]
I think this issue can be closed, it's fixed on #145

**Comment by Sloy** [comment]
U right, thanks!
