### ISSUE TITLE
Make the FlakyTestRule independent from ActivityTestRule

### ISSUE THREAD

**Issue by Sloy** [SchibstedSpain/Barista#131]
As noted by @CristianGM, our `FlakyTestRule` extends `ActivityTestRule` but there's no reason to do it. It would work as an independent rule too.

It's this way because of historic reasons of how we found a solution to the problem, but no longer needed.

Thanks @CristianGM for the heads up! 
_(and next time maybe open an issue or PR 😛)_

**Comment by Sloy** [comment]
For retrocompatibility I think we should deprecate the current one but leave it as it is, and create a new simpler one. They can probably reuse some code though.

**Comment by SmasSive** [comment]
I agree @sloy!
