### ISSUE TITLE
Add pullToRefresh method without id

### ISSUE THREAD

**Issue by Sloy** [SchibstedSpain/Barista#133]
Currently the pull to refresh method (named `refresh()`) requires the layout id as a parameter. In most cases when there's only one SwipeRefreshLayout in screen there's no need to pass the id.

We can infer the view with a `isAssignableFrom(SwipeRefreshLayout.class)` matcher, so the id parameter wouldn't even be needed. We can still leave the the method with the parameter, just in case someone needs it.

**Comment by rocboronat** [comment]
Noice!

**Comment by EsteveAguilera** [comment]
This issue can be closed, it was fixed on #150

**Comment by Sloy** [comment]
Yey!
