### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by bkmalkoc** [SchibstedSpain/Barista#135]
Do you allow to take screenshot during test cycle?

**Comment by rocboronat** [comment]
Yes. In my personal case, I use Fastlane to take them. Does this answer your question? 😌

**Comment by bkmalkoc** [comment]
Could you please give an example or exact documentation for it? @rocboronat

**Comment by Sloy** [comment]
Hi @bkmalkoc! We don't provide a specific way of taking screenshots with Barista, but you can use any other library you like for that.
For example, [Composer](https://github.com/gojuno/composer) or [Spoon](https://github.com/square/spoon/).

However be aware: if you want to take screenshots on test failures, you should wait until https://github.com/SchibstedSpain/Barista/issues/116 is resolved.

**Comment by Sloy** [comment]
Does this answer your question @bkmalkoc?
