### ISSUE TITLE
Improve flakiness of scrollTo action

### ISSUE THREAD

**Issue by Sloy** [SchibstedSpain/Barista#142]
Let's face it: Espresso's scrollTo action doesn't always work. We're not sure why, but it doesnt. That's why we have 50-100 retries on BaristaScrollActions.

This approach works (thanks a lot @rocboronat!), but it has some drawbacks. We retry even if the scroll *did* work, so we make tests a bit slower. Also, each retry floods the logcat with messages warning that there's no need to scroll. It's not a big deal (right @CristianGM?), but it can be improved.

Espresso ScrollToAction has some code in place to verify that the scroll was done, and it fails if it didn't work. We could fork that code and add the retries there. That would make Barista [faster, better and stronger](https://www.youtube.com/watch?v=gAjR4_CbPpQ).

**Comment by rocboronat** [comment]
Sounds great!

**Comment by Sloy** [comment]
Duplicated: https://github.com/SchibstedSpain/Barista/issues/115
