### ISSUE TITLE
Update the README when merging Barista 2

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#151]
Let's wait until the branch is merged... :·)

**Comment by Sloy** [comment]
Yeh, the readme has to be completely updated for Barista 2.0. 
I'm accumulating everything until I finish the public API refactoring.

But thanks for the issue, that way we won't forget :)

**Comment by rocboronat** [comment]
Let's change the shape of the issue, then :·D

[ ] Add the new focus assertions to the README.md

**Comment by Sloy** [comment]
Updated at https://github.com/SchibstedSpain/Barista/pull/163

**Comment by Sloy** [comment]
Done!
