### ISSUE TITLE
Choose a codestyle

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#154]
When we started the project, I think we were using the Square Code Style (https://github.com/square/java-code-styles). But now, the groovy and xml files are 4-4-8. And I'm getting mad.

Let's choose one code style, and reformat the whole project with it. In the meantime, sorry if I restyle the `AndroidManifest.xml`... 😢

**Comment by Sloy** [comment]
We're using Schibsted's internal codestyle

**Comment by rocboronat** [comment]
@sloy what do you think about using a open codestyle? It will help other contributors to contribute. Yesterday I was fixing autoformatter by hand 😵

**Comment by Sloy** [comment]
I'll raise the issue internally to the Schibsted team. I agree we really should either publish our codestyle or use a public one, it's not helpful at all for contributors to use a private codestyle.

**Comment by EsteveAguilera** [comment]
Barista2 is out! It might be a good time to talk about the codestyle :D

**Comment by Sloy** [comment]
How about just using this new shiny official style?: https://android.github.io/kotlin-guides/style.html

**Comment by EsteveAguilera** [comment]
what about this one:
https://github.com/aosp-mirror/platform_development/blob/master/ide/intellij/codestyles/AndroidStyle.xml

**Comment by EsteveAguilera** [comment]
I've just seen that the Square Code Style (https://github.com/square/java-code-styles) has recently included the Android Kotlin style guide updates... so it might be a good choice...

**Comment by Sloy** [comment]
I'll soon include the Schibsted's codestyle into the repo for Kotlin, Java and xml. I don't forget about you @EsteveAguilera ❤️
