### ISSUE TITLE
assertNotDisplayed(R.id.view, "Hello world")

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#164]
Let's do the opposite of https://github.com/SchibstedSpain/Barista/issues/120, where we created `assertDisplayed(id,text)`

**Comment by Sloy** [comment]
Hmmm is that really useful? I mean...
`assertNotDisplayed("Hello World")` already covers that case.

**Comment by EsteveAguilera** [comment]
Ahhh.... hmmm... you're right... 
The issue started at #163 and never thought about that...
It's useful for the README but useless for the library 🕺

**Comment by rocboronat** [comment]
It's the moment to start tracking witch methods are used by the users 🙌🏻 BTW, I think this case could be useful to check the labels of checkboxes that change their label when selected, and the only thing they show is the word "checked" or "unchecked". I will send you a screenshot tomorrow by a sexy private way.

**Comment by EsteveAguilera** [comment]
Oh, you're right @rocboronat! 🤘

**Comment by rocboronat** [comment]
Hey! Today I thought that I can also check the opposite. Instead of isNot("checked"), check is("uncheked"). But @Sloy , #165 just adds 4 lines of production code and 8 lines of tests. Let's move on increasing the public API and delete it if no one used it for some time.

**Comment by Sloy** [comment]
> and delete it if no one used it for some time

That's not gonna happen 😂 
We can't really know which methods people use. 

But anyways, let's go with it since the PR is already opened. It's not that harmful. 👍
