### ISSUE TITLE
Create a assertContains("text") or modify the current assertDisplayed to match containing strings

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#166]
Right now, there's not a way to assert that this RadioButton contains the text "Cantidad: 1".

![image](https://user-images.githubusercontent.com/456499/33026702-5048bbce-ce11-11e7-9114-c7b6738394db.png)

BTW, I tried to write the whole text at the `assertDisplayed()`, including the `\n`, but it failed.

So, I propose to create a new method to check if a text is contained, or modify the well-known `assertDisplayed` to match if the given text is not exact, but contained.

**Comment by alorma** [comment]
Are you working on this one @rocboronat ?

**Comment by alorma** [comment]
I take it :D

**Comment by rocboronat** [comment]
If you're going to start working on it, create your branch from barista2. There's where @Sloy is doing a big refactor.

**Comment by rocboronat** [comment]
Crossed messages! Great @alorma , it will be really useful :·)
