### ISSUE TITLE
Change the ViewPager methods to apply only on displayed widgets

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#17]
In one case, we have a ViewPager inside a ViewPager. Then, the ViewPager that we want to move is repeated over lots of times inside another ViewPager. That makes Espresso to launch a "multiple ViewPagers match that ID". But well, obviously, we want to interact with the ViewPager that is visible.

So:

`onView(allOf(ViewMatchers.withId(R.id.the_id), ViewMatchers.isDisplayed())).perform(
            new ViewAction[] { ViewActions.swipeLeft() });`

**Comment by rocboronat** [comment]
@Sloy I'll love to have feedback on this idea :·D

**Comment by Sloy** [comment]
Wut? A ViewPager inside a ViewPager both with the same id? That sounds wrong :/

**Comment by rocboronat** [comment]
Nope, a ViewPager that contains a page that has a ViewPager. So, the ID of the second ViewPager will appear in every page of the first ViewPager, so it will be repeated in the hierarchy tree.

**Comment by rocboronat** [comment]
Something like this, where the car image is inside a small ViewPager that show lots of pictures of that car, while you can also change the page to take a look to another car:

![2017-02-16 17 13 34](https://cloud.githubusercontent.com/assets/456499/23032108/b3835438-f473-11e6-8842-e7da89f3dcc2.png)

If you want to swipe the images' ViewPager, you has match by ID and also look only for displayed ViewPagers.

**Comment by Sloy** [comment]
Now I get it.
I don't have a strong opinion about this...
Seems like adding the isDisplayed is a hack for a specific case. And not only for the ViewPager methods. What about the buttons? Or any other view in that page?

**Comment by rocboronat** [comment]
Yes, totally. It could apply to lots of things. But, excepting in the Buttons where we do the magic of scrolling until needed, when are you interested in tapping a button that is not visible? 

Something to thing about it. No hurries, by the way.

**Comment by rocboronat** [comment]
Done at #51 !
