### ISSUE TITLE
assertNotDisplayed(id, text) Not exist

### ISSUE THREAD

**Issue by alorma** [SchibstedSpain/Barista#178]
I see on the readme, the method `assertNotDisplayed(id, text)` but I don't see in the code.

Should we remove it? Or add the case?

**Comment by EsteveAguilera** [comment]
Was added on #165... maybe we lost it on the migration to barista2?

**Comment by alorma** [comment]
@Sloy ?

**Comment by EsteveAguilera** [comment]
@alorma @Sloy I've tried to figure out where did we lost that assertion, but there has been a lot of big changes in the code recently...

@Sloy do you want me to open a new PR with this assertion again, or should I spend a little more time browsing commits? 👼

**Comment by Sloy** [comment]
Oh hi, sorry I forgot this was here!
Maybe just open a PR doing a cherry pick of https://github.com/SchibstedSpain/Barista/commit/8f577a03438c034a97298859354677bc7f976309

`git cherry-pick 8f577a03438c034a97298859354677bc7f976309`

Maybe it will have conflicts because of the readme and so on :/

**Comment by EsteveAguilera** [comment]
On #171 you've moved a lot of things... and a lot of code has changed since the #165 

I think copy/paste will be easy than a cherry-pick and conflicts fight 🐛

**Comment by Sloy** [comment]
Ouch you're right. Sorry 😢

**Comment by EsteveAguilera** [comment]
It is not a big loose taking into consideration all the things you've changed/moved/refactor, so no need to be sorry at all! 🎉
