### ISSUE TITLE
Missing actions for GridView

### ISSUE THREAD

**Issue by jamesbluecrow** [SchibstedSpain/Barista#187]
I know that now days nobody uses the old `GridView`, but we do have an old screen where we do have it and I just realized that Barista misses actions for it.

Since `GridView` and `ListView` both inherit from `AbsListView` giving support for it will be super simple. I'm going to open soon a PR with a proposal.

**Comment by Sloy** [comment]
Done! Will be out in the next release. Thanks @jamesbluecrow ❤️
