### ISSUE TITLE
Missing swipeLeft and swipeRight actions

### ISSUE THREAD

**Issue by jamesbluecrow** [SchibstedSpain/Barista#193]
While working at my company today it turned out that we need those interactions and they are missing in the library.

I'll create them today.

**Comment by rocboronat** [comment]
@jamesbluecrow hi again after some months! :·)

Do `swipeViewPagerForward()` and `swipeViewPagerBack()` give the behavior you wanted? If so, please close the issue. Thanks a lot!

**Comment by jamesbluecrow** [comment]
Hey @rocboronat !

Yeah, I think they fully cover the scenario I mentioned. Thanks!


Keep it up!
