### ISSUE TITLE
Where is BaristaVisibilityAssertions.assertContains ??

### ISSUE THREAD

**Issue by Aetherna** [SchibstedSpain/Barista#199]
It's shown in the docs, it's shown in the samples as:

import com.schibsted.spain.barista.assertion.BaristaVisibilityAssertions.assertContains

I can't find it in 2.1.0?

**Comment by Sloy** [comment]
The feature is merged in master but not released yet.
I just launched a new release, give Travis a couple of minutes to make it and you'll have it as 2.2.0 😃 

Sorry for the confusion there.

**Comment by Sloy** [comment]
There you go @Aetherna! It's released now. Try with the new version.

Thanks for the heads up :)

**Comment by EsteveAguilera** [comment]
I think this issue can be closed

**Comment by rocboronat** [comment]
No news in a month... let's close it! :·)
