### ISSUE TITLE
Better have withIndex feature.

### ISSUE THREAD

**Issue by talentprince** [SchibstedSpain/Barista#202]
If a viewgroup contains multiple views, with same id, we need to pick by position, but espresso only support adapter view.
So we need to custom one, hope you can add this feature.

**Comment by Sloy** [comment]
I'm not sure if I understand what you mean. Could you provide an example?

**Comment by talentprince** [comment]
like, viewgroup contains three molecule, so all the molecules get the same id.
I want to test the second one with `withId` but can not get specific one.

**Comment by Sloy** [comment]
My first thought would be to avoid using the id to match the view, and instead use some other unique property of that view, like the text.
However, if position is really really your only option, [there's a ViewMatcher](https://github.com/SchibstedSpain/Barista/blob/master/library/src/main/java/com/schibsted/spain/barista/internal/matcher/HelperMatchers.java#L12) for that in Barista's internal API called `HelperMatchers.atPosition(position, matcher)`. It's currently used for RadioButtons.

Does it solve your problem? Or are you suggesting something different like adding the position to a specific public method? We have many public interactions and assertions, I think adding a withIndex parameter to all of them would be out of the scope of the library. But maybe I'm just misunderstanding.

**Comment by Sloy** [comment]
I'm going to close the issue for inactivity. Feel free to reopen if you find the proposed alternative doesn't fit.
Also, might be solved with https://github.com/SchibstedSpain/Barista/issues/224 too.
