### ISSUE TITLE
Better Kotlin support

### ISSUE THREAD

**Issue by LPFinch** [SchibstedSpain/Barista#204]
Please simplify BaristaRule
Some example
```kotlin
inline fun <reified T : Activity> create(): BaristaRule<T> = BaristaRule.create(T::class.java)
```
After that code looks like 

```kotlin
@Rule
val rule = create<AwesomeActivity>()
```

**Comment by alorma** [comment]
Closed on https://github.com/SchibstedSpain/Barista/pull/205

Thanks!

**Comment by Sloy** [comment]
Thanks @LPFinch for the idea and @alorma for the PR :)
