### ISSUE TITLE
Add more options to view pager actions

### ISSUE THREAD

**Issue by Serchinastico** [SchibstedSpain/Barista#210]
Hey there,

From Karumi, we've been playing with your library for a while and, first of all, let me say that it's awesome, thank you all for saving us some precious time!

We found some very specific scenarios where the view pager actions didn't work out for us, though.
1. We've been working with view pagers that are not completely visible on the screen. For that case, we had to create our own `GeneralSwipeAction` copy to be able to ignore the visibility requirement (see [the original implementation](https://android.googlesource.com/platform/frameworks/testing/+/android-support-test/espresso/core/src/main/java/android/support/test/espresso/action/GeneralSwipeAction.java#40) where it forces the swipe action to apply iff the 90% of the view is on the screen).
2. The other workaround we came with is to make it possible to change the initial/end position of the gesture itself. The problem being that we had a view pager AND a drawer in the same screen. Starting the movement from the left side of the screen would open the drawer and doing it from the center of the view wouldn't go to the next page when running on slow environments (I'm looking at you, CI  👀).

Would you be interested on adding those features to Barista?

**Comment by Sloy** [comment]
Hi @Serchinastico!
Sure, they seem like helpful additions 😃 

Do you think adding your workaround to the current Barista methods would work without breaking other things? Or would you add them as separate new methods?

**Comment by Serchinastico** [comment]
I guess the two features would break some way or another people's code. The first one is safer IMO but who knows if anyone is relying on a view pager to be 90% percent to fail the test (¯\\\_(ツ)_/¯). The second one needs additional input data (something like two [0-1] values to specify where to start and end the swipe gestures) so I'd add them as different methods.

**Comment by Sloy** [comment]
Hi @Serchinastico? Are you still interested in adding those features? Or should we close the issue? 
No hurt feelings, is just to keep the issue list cleaner :p

**Comment by Serchinastico** [comment]
Hi @Sloy,

Yeah, I'm still interested! I just didn't give it the priority it deserved. Let's do something, I'm going to try send you a PR this weekend, if I don't, feel free to close it, how does that sound to you?

Sorry about keeping this issue open for so long 🙏 .

**Comment by Sloy** [comment]
Of course, no problem!

Don't worry about it, happens to all of us 😂
