### ISSUE TITLE
Check if ImageView is displaying a Bitmap

### ISSUE THREAD

**Issue by nmwilk** [SchibstedSpain/Barista#211]
To test display of images that are not in resources. E.g. when an app downloads content and loads from file.

**Comment by alorma** [comment]
Hi @nmwilk 

You can use `assertHasAnyDrawable(R.id.image_view);` to check if a given ImageView has a drawable

**Comment by nmwilk** [comment]
Hi @alorma. Thanks, but I want to assert that a specific Bitmap is displayed in an ImageView.

**Comment by Sloy** [comment]
Closing it, since we didn't find a solution that works in a deterministic way. 

Manual checks can still be done with https://github.com/SchibstedSpain/Barista/pull/254
