### ISSUE TITLE
Idling resources missing.

### ISSUE THREAD

**Issue by RanaJakka** [SchibstedSpain/Barista#214]
some the views are needed to wait for network calls. So in those cases, main thread needs to wait for network callbacks. I know we have methods call wait(milliSeconds), but we don't know how much time its get network response. So is there any api for handling network calls?

**Comment by Sloy** [comment]
Hi @RanaJakka,
The best way to wait for async operations is with Idling Resources.
Since Barista is built on top of Espresso you can just use them.

**Comment by rocboronat** [comment]
I'm closing it because it was a question, it was answered, and the issue is totally idle.
