### ISSUE TITLE
androidTestCompile -> androidTestImplementation

### ISSUE THREAD

**Issue by nanodeath** [SchibstedSpain/Barista#217]
When I compile with the current Android Studio (3.1.2) using `androidTestCompile` (per the recommendation in the README.md), the compiler spits out

```
Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'androidTestApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```

Replacing `androidTestCompile` with `androidTestImplementation` seems to work and makes the error go away.

**Comment by Sloy** [comment]
Thanks for the heads up! Fixed now 😄
