### ISSUE TITLE
Add hasErrorText to BaristaEditTextIteractios

### ISSUE THREAD

**Issue by diogosq** [SchibstedSpain/Barista#218]
Hello everyone

I noticed that BaristaEditTextIteractios  does not have a check if edittext has an error message with a specific text.

So I created an extension for that. If it's of interest ...

```kotlin
fun BaristaEditTextInteractions.hasErrorText (@IdRes editTextId: Int, text: String) {
     BaristaScrollInteractions.safelyScrollTo (editTextId)
     Espresso.onView (DisplayedMatchers.displayedAnd (ViewMatchers.withId (editTextId)).) Check (ViewAssertions.matches (hasEditeTextErrorText (text)))
}

fun hasEditeTextErrorText (expectedErrorText: String): Matcher <View> {
     return object: TypeSafeMatcher <View> () {

         public override fun matchesSafely (view: View): Boolean {
             if (view! is EditText) {
                 return false
             }

             val error = view.error

             return error! = null && expectedErrorText == error.toString ()

         }

         override fun describeTo (description: Description) {}
     }
} ```

**Comment by Sloy** [comment]
Hi @diogosq! Thanks for the heads up and the code.
I think this will be addressed with the changes from PR #223. It includes `assertError` functions that checks for both EditText and TextInputLayout errors. 

We'll set this issue as resolved when that code is merged :)

**Comment by Sloy** [comment]
Done in #236 thanks to @DeanPike! It will be available in the next release.

**Comment by diogosq** [comment]
Nice! :-)
