### ISSUE TITLE
Scroll to a R.string.text

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#22]
BaristaScrollActions.scrollTo(R.string.text) doesn't have any implementation

**Comment by rocboronat** [comment]
Bump! We need this to make this test locale independent:

![image](https://user-images.githubusercontent.com/456499/33031956-0e2bd802-ce20-11e7-9f5c-5d74a6b81ad0.png)

**Comment by rocboronat** [comment]
Barista 2.0 lost this method 😢

**Comment by Sloy** [comment]
😮  But but but but... https://github.com/SchibstedSpain/Barista/pull/169 What happened?

**Comment by rocboronat** [comment]
Don't know :|

**Comment by rocboronat** [comment]
Don't worry, working on it right now

**Comment by rocboronat** [comment]
Done at #176 !
