### ISSUE TITLE
Assert displayed with string resource id

### ISSUE THREAD

**Issue by tiagoalmeida92** [SchibstedSpain/Barista#246]
Would be nice to do text assertions with the resource id instead of String.

I would gladly submit a pull request if this is something you think it makes sense to add.

```
@JvmStatic
fun assertDisplayed(@IdRes viewId: Int, @StringRes textId: Int) {
   viewId.resourceMatcher().assertAny(withText(textId))
}
```

**Comment by alorma** [comment]
HI @tiagoalmeida92 

Yes, this sounds good for Barista!

Thanks!

**Comment by tiagoalmeida92** [comment]
I can't push to the repo, are PRs enabled?

**Comment by EsteveAguilera** [comment]
PRs are enabled, but you can not push on this repo because you're not an owner...

You've to create a fork of the repo, create a new branch in your fork, push the new code there and then create a PR from this new branch on your repo to the original repo.

**Comment by tiagoalmeida92** [comment]
Thanks! Didn't know, will do the fork.

**Comment by tiagoalmeida92** [comment]
PR added #247

**Comment by rocboronat** [comment]
This feature was merged some months ago. Thanks for the contribution, @tiagoalmeida92 ! 👍
