### ISSUE TITLE
How to click on Floating Action Button using Barista

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [SchibstedSpain/Barista#251]
I'm using this third party FAB com.github.ag.floatingactionmenu.OptionsFabLayout.  How can i click on this Floating Action Button using Barista

**Comment by Sloy** [comment]
Hi. I don't know about that library. But you should be able to do it if the buttons have their own id.
You should probably ask in the library project itself how to achieve it. Either with Barista or Espresso.
