### ISSUE TITLE
can i combine espresso and barista code ??

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [SchibstedSpain/Barista#252]
i already have some code in espresso, now if i move to barista, do i need to rewrite everything or can i combine espresso test code and barista test code ??

**Comment by Sloy** [comment]
Absolutely. Barista is just a layer above Espresso. But it uses Espresso underneath. So yes, you can totally combine them. 😃 

We do it as well in our projects. We use Barista for simpler common things, and Espresso for corner cases where Barista isn't enough.
