### ISSUE TITLE
Improve the 'message' paramenter name of the custom assertions

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#258]
Hi everyone!

Some days ago, I created and merged #256. I thought it was a good approach, but as @Sloy explained in #255, the proposal `assertionErrorMessage` is less intuitive than the previous one.

I had some ideas about the best name for this parameter, but I prefer to discuss it in this issue than doing it in a PR, to save some time on the code itself.

So! Here are some options and what I think about them:

- `message` is not the best because it's too broad. I totally misunderstood its meaning twice...
- `assertionErrorMessage` is bad because the user will understand that the message explains what was wrong with the check, instead of what was the check expecting.
- `assertionDescription` is it good enough? Probably people won't understand that its reason to exist is just to be shown when the assertion fails.
- `assertionHumanReadableDescription`: the easier to understand, but too long. Not fancy.

Right now my opinion is to go on with `assertionDescription`, but please share your thoughts... there's an umbeatable best option there and we should put it on our API. I think the custom assertions system is a game changer either for the users and for us as developers, so having a great parameter name there is near to mandatory.

Thanks a lot, @Sloy @alorma @SmasSive and whoever who wants to share their ideas! :tada:

**Comment by Sloy** [comment]
I'd go with `assertionDescription` too

**Comment by Sloy** [comment]
PR opened!
