### ISSUE TITLE
Create one rule that uses the other Barista ones

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#26]
Just a way to ease copypasting to newcomers

**Comment by rocboronat** [comment]
It could be great to also add the common `MockitoRule`

**Comment by Sloy** [comment]
I'm on it!
We decided that it's better to not include MockitoRule because it's unrelated to espresso, the rule ordering doesn't matter, and it can cause issues with DexMaker (that's another story).

**Comment by rocboronat** [comment]
Done at #90 by @Sloy !
