### ISSUE TITLE
Clear app SharedPreferences , Database and files are not working with me

### ISSUE THREAD

**Issue by moatazeldebsy** [SchibstedSpain/Barista#274]
Clear app SharedPreferences , Database and files are not working with me
```
// Clear all app's SharedPreferences
    @Rule
    public ClearPreferencesRule clearPreferencesRule = new ClearPreferencesRule();

    // Delete all tables from all the app's SQLite Databases
    @Rule
    public ClearDatabaseRule clearDatabaseRule = new ClearDatabaseRule();

    // Delete all files in getFilesDir() and getCacheDir()
    @Rule
    public ClearFilesRule clearFilesRule = new ClearFilesRule();

```

**Comment by moatazeldebsy** [comment]
Hi @alorma m than you for replay, I'm using the following :
Barista = latest 
Espresso Version= 3.1.0
androidX = 1.1.0

Actually, the scenario that I'm using I want to run 2 test cases and my app start with set my location and then I logged in, in the next test case I must start as the first one without location and log out from the app, so when I used these rules nit working with me

**Comment by moatazeldebsy** [comment]
Another question where I can put this line

`PermissionGranter.allowPermissionsIfNeeded(Manifest.permission.GET_ACCOUNTS);` and this is what I need as a permission or I need to change Get account to what I need

**Comment by Sloy** [comment]
Hi @moatazeldebsy.  How are you starting your activities in the test? Take into account that Espresso's ActivityTestRule by default will launch the Activity before your test method starts. If JUnit is running the activity rule before Barista rules you might get an inconsistent behaviour.

You need to **make sure** that Barista rules run before your activity opens. I recommend using RuleChains to enforce the order in which they run, and setting ActivityTestRule's parameter `launchActivity` to false, so you can manually launch the activity from your test method.

Take a look at how [BaristaRule](https://github.com/SchibstedSpain/Barista/blob/master/library/src/main/java/com/schibsted/spain/barista/rule/BaristaRule.kt#L44) uses a RuleChain to make sure they run in the right order. Or [this example](https://github.com/SchibstedSpain/Barista/blob/master/sample/src/androidTest/java/com/schibsted/spain/barista/sample/ClearPreferencesRuleTest.java) of how to run the ClearPreferencesRule before the activity opens.

**Comment by Sloy** [comment]
I'm guessing you solved the issue, so I'm closing it. Feel free to reopen if you have any other issues.
