### ISSUE TITLE
Old branches

### ISSUE THREAD

**Issue by alorma** [SchibstedSpain/Barista#275]
Hi @SchibstedSpain/barista-maintainers !

Looking at branches tab from github (https://github.com/SchibstedSpain/Barista/branches) i just seen that there are so old ones:

`docpress` Updated a year ago by @Sloy
`barista2` Updated a year ago by @rocboronat
`pr/223` Updated 7 months ago by @Sloy

So... can we remove those ones?

**Comment by Sloy** [comment]
keep docpress, the other ones are obsolete now

**Comment by alorma** [comment]
Done!
