### ISSUE TITLE
Automatically disable animations for tests

### ISSUE THREAD

**Issue by headsvk** [SchibstedSpain/Barista#278]
[Espresso guidelines](https://developer.android.com/training/testing/ui-testing/espresso-testing#setup) suggest turning off animations before running tests.
I found [this useful rule](https://proandroiddev.com/one-rule-to-disable-them-all-d387da440318) that disables animations before running tests and enables them afterwards.

It only works for API 21+ but I think it could be a nice addition to Barista.

**Comment by Sloy** [comment]
Hi @headsvk, sorry for the delayed response. 
That's pretty cool! I wasn't aware that animations can be disabled via UiAutomator.

At Schibsted Spain we already have the animations issue solved in our own device farm, but I too think it would be a nice addition to Barista.

Would you like to submit a PR with such feature?

**Comment by headsvk** [comment]
Hey @Sloy,
I just noticed that the author @blipinsk made a library out of it:
https://github.com/blipinsk/disable-animations-rule

Do you want to include it or customize the code?
The library is defined with min sdk 14 but I expect including the rule will just crash the test below 21.
Instead we could make it fail silently and just write an error message to console.
Or just wrap it in `@RequiresAPI(21)`.

What do you think?

**Comment by blipinsk** [comment]
> The library is defined with min sdk 14 but I expect including the rule will just crash the test below 21.
> Instead we could make it fail silently and just write an error message to console.
> Or just wrap it in `@RequiresAPI(21)`.

The library shouldn't crash below 21, it should just do nothing.
More on the reason for `minSdk` `14` is in the [Compatibility section](https://github.com/blipinsk/disable-animations-rule#compatibility).

**Comment by Sloy** [comment]
Ah! Nice work @blipinsk! 👏 
@headsvk if he already published the library then I guess there's no need for duplicating it on Barista. But thanks for the recommendation anyways! It was a good discovery :)
