### ISSUE TITLE
No assertion to check spinner selection value or text

### ISSUE THREAD

**Issue by hfauche** [SchibstedSpain/Barista#279]
I can't find any way to check a spinner selection.
`BaristaVisibilityAssertions.assertDisplayed` does not work.
With espresso I have to use `withSpinnerText` like:
`onView(withId(R.id.roleCountryCodeSpinner)).check(matches(withSpinnerText(country.toString())));`
So may be a special assertion method for spinners that wraps `withSpinnerText` could be added.

**Comment by Sloy** [comment]
You can use the new assertDisplayed introduced in 2.8.0 which admits a matcher as a parameter. 
So you can do `assertDisplayed(withSpinnerText("Banana"))`.

I just released 2.8.0 a few minutes ago, it should already be available for downloading :)
