### ISSUE TITLE
Accept text when it's in uppercase, to speed up testing

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#28]
If `R.string.search = "Search"` but the screen shows `SEARCH` for some design decision, having a `assertDisplayedIgnoreCase` makes things simpler.

@Sloy what do you thing about this? Probably I'm too aggressive making things easy... ?

**Comment by Sloy** [comment]
Hmm do we actually care to distinguish between uppercase and lowercase? The default could be ignoreCase, and an optional matchCase.

I don't see a reason to not ignore by default, we're trying to make assumptions for the client so Barista is more predictable than Espresso.

**Comment by rocboronat** [comment]
So @Sloy, your proposal is to change `assertDisplayed` to accept all casing, and create a new method `assertDisplayedMatchingCase`?

**Comment by Sloy** [comment]
It is!

**Comment by rocboronat** [comment]
Nice! Thanks for the feedback! :·)

**Comment by Sloy** [comment]
Hi! I think my proposal has changed after a few months :P 
Instead of adding another method, I would prefer doing https://github.com/SchibstedSpain/Barista/issues/224, which lets people use Barista for more special cases without needing to have 100 methods in the API.

**Comment by rocboronat** [comment]
I think it's not the same. It won't fix the buttons' autocapitalize feature.

BTW, I'm going to close this issue. It's very old, asserting a button's text is not as common as that, and we could reopen it in the future if we need it again. So... close!
