### ISSUE TITLE
Missing contains assertions using String resource

### ISSUE THREAD

**Issue by EsteveAguilera** [SchibstedSpain/Barista#292]
**Description what you'd like to happen:**

The `assertContains` and the `assertNotContains` can be used only with a string text.

It will be usefull to be able to use them with a String resource Id

**Comment by karadkar** [comment]
@Sloy Can I take this up?

**Comment by alorma** [comment]
Sure @karadkar , PRs are welcome on this project :D

**Comment by karadkar** [comment]
Please check #305

**Comment by EsteveAguilera** [comment]
Fixed and merged on #305, I'm closing the issue!

Thanks @karadkar 🎉
