### ISSUE TITLE
https://schibstedspain.github.io/Barista/ is outdated

### ISSUE THREAD

**Issue by EsteveAguilera** [SchibstedSpain/Barista#293]
**Describe the Bug:**
Update https://schibstedspain.github.io/Barista/ to include recent changes on the Readme.md

**Comment by rocboronat** [comment]
My vote to maintain only one documentation ☝️

**Comment by Sloy** [comment]
I was going to say the same. Unless that page is generated automatically, I would prefer to not maintain it.

I was playing around with that some time ago and abandoned it, sorry. I should have deleted it :(

**Comment by Sloy** [comment]
Deleted ✅
