### ISSUE TITLE
Pass Espresso tests on some Continous Integration platform

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#3]
For some reason, the instrumental tests fails on the public Travis. We must fix it to guarantee Barista's confidence.

**Comment by Sloy** [comment]
This is fixed by https://github.com/SchibstedSpain/Barista/pull/83

Can we close this issue now @rocboronat? Or do you want to keep it opened while we verify that tests on CI are stable?

**Comment by rocboronat** [comment]
True! Let's close it to keep the issue list clean. If the solution is not reliable, we can reopen it for free :·D

Thanks for spotting it!
