### ISSUE TITLE
Feature Request: Support Assertion for TextInputLayout hint helper attribute

### ISSUE THREAD

**Issue by IanArb** [SchibstedSpain/Barista#302]
Hi,

It would be nice addition to have a hint helper assertion wrapper like we have for assertError(). This is useful when we wish to assert for any success or helper messages inside our text input layouts.

I can start implementing this assertion feature and open a PR.

**Comment by IanArb** [comment]
Already implemented a solution and ready to open a PR if granted access.

Example snippet 

`object BaristaHelperTextAssertions {
    @JvmStatic
    fun assertHelperHintText(@IdRes viewId: Int, @StringRes text: Int) {
        val resourceString = InstrumentationRegistry.getTargetContext().resources.getString(text)
        assertHelperHintText(viewId, resourceString)
    }

    @JvmStatic
    fun assertHelperHintText(@IdRes viewId: Int, text: String) {
        ViewMatchers.withId(viewId).assertAny(matchHelperText(text))
    }

    private fun matchHelperText(expectedHelperHintText: String): Matcher<View> {
        return object : TypeSafeMatcher<View>() {
            override fun describeTo(description: Description) {
                description.appendText("with helper hint text: ").appendText(expectedHelperHintText)
            }

            override fun matchesSafely(item: View): Boolean {
                return when (item) {
                    is TextInputLayout -> expectedHelperHintText == item.helperText.toString()
                    else -> {
                        throw UnsupportedOperationException("View of class ${item.javaClass.simpleName} not supported")
                    }
                }
            }
        }
    }
}`

**Comment by alorma** [comment]
Hi @IanArb 

Thanks for the issue, and for a solution!

You can fork this project and open a PR directly into Barista, we would look at it 🎉

**Comment by IanArb** [comment]
@alorma 

Thanks just forked the repository and created a PR directly to the project.

**Comment by alorma** [comment]
Fixed on #303
