### ISSUE TITLE
Feature request: clickOn image should be able to take a string to match contentDescription

### ISSUE THREAD

**Issue by kenyee** [SchibstedSpain/Barista#304]
**Description what you'd like to happen:**
Sometimes you want to be able to click on an image or layout w/ a contentDescription set to text because if your app was properly set up for accessibility, it would have these fields set when an image is set dynamically on it (e.g. in a Recyclerview or a dynamically created list of items whose order might change at runtime so you can't use the item index easily).
Currently, Barista doesn't have any methods to do this...I'd suggest maybe something like this for an API:

clickOnDescription(R.string.something)
clickOnDescription(textstring)

Yes, I know...do a PR :-)
Just want to finalize a possible API here before doing that...

**Example espresso code if available**
```
            onView(withContentDescription(DateCellViewHolder.getContentDescription(getApplication(), today)))
                    .check(matches(isEnabled()))
```

**Comment by alorma** [comment]
I see two options here.

One is to create something like `clickByContentDescription()` that is not much `barista magic` really...

and another option is to just improve the `clickOn(R.string)``clickOn("...")` methods, to also check content description

What do you think @Sloy ?
