### ISSUE TITLE
assertDisplayed doesn't work when multiple views matches the text

### ISSUE THREAD

**Issue by Sloy** [SchibstedSpain/Barista#37]
We found a case that I think Barista should handle.
In an Activity we had multiple views with the same text "Banana", and we were doing `assertDisplayed("Banana")` to verify that the data had been loaded and displayed.

Espresso fails because multiple views match the condition `withText()`.

From the perspective of someone using Barista and reading the method `assertDisplayed`, I think it should work. What do you guys think???

**Comment by rocboronat** [comment]
Totally agree 😄

**Comment by SmasSive** [comment]
Sorry but I don't understand what you are trying to say @Sloy ...
You are doing `assertDisplayed("Banana")` right? but Espresso fails... And AFAIK Barista is a wrapper of Espresso so, if Espresso fails, Barista should fail too.

But for sure I misunderstand something 💃

**Comment by rocboronat** [comment]
Nope. The thing is why it's failing, @SmasSive . In the context @Sloy given, the app is showing "Banana" several times. As a Barista user, if I want to check if the text "Banana" is there, if there are lots of "Banana", `assertDisplayed("Banana")` should give a green, not an Exception.

**Comment by SmasSive** [comment]
Yeah! Then I agree with you both :dancing_men:

**Comment by rocboronat** [comment]
Then... it's PR time! :tada: hehehe

**Comment by Sloy** [comment]
Exactly, sorry for the bad explanation 😅 

"Banana" appears twice in that screen, let's say it's the title of the screen and also a TextView inside the layout.

With espresso, if you run 
`onView(withText(text)).check(matches(isDisplayed()));`
and it finds two views with the text "Banana", it fails.

My point is: from the perspective of a Barista user, `assertDisplayed()` means it's displayed any number of times, the name of the method doesn't imply the other restriction.

Better @SmasSive ?

**Comment by Sloy** [comment]
LOL I see I was too slow writing my comment, you both already answered :partyparrot:

**Comment by rocboronat** [comment]
Welcome to the party, @Sloy ! Take some ice with you 🍸 🍹

**Comment by SmasSive** [comment]
Jajaja @sloy now your explanation is perfect! 
So let's code it out!

**Comment by Sloy** [comment]
Ideas?
We solved it by wrapping the `withText("Banana")` matcher inside a `firstOf(withText("Banana"))` matcher.
But it wouldn't work if the first banana is hidden and the second one is displayed.

**Comment by Sloy** [comment]
There goes my idea: https://github.com/SchibstedSpain/Barista/pull/38

**Comment by rocboronat** [comment]
Done by @Sloy !
