### ISSUE TITLE
Accepting multiple permissions at once

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#45]
As @knezmilos explains at a StackOverflow question, if using multiple permissions at the same time, the indexes get shifted - 0 is nothing (false), 1 is deny and 2 is allow. So, our PermissionGranter doesn't work as expected.

The complete thread, here: http://stackoverflow.com/questions/33929937/android-marshmallow-test-permissions-with-espresso

**Comment by v1sar** [comment]
It's fixed long time ago with https://github.com/SchibstedSpain/Barista/commit/1c7f1889763402b0333ac3e467f6753454a4cb1d
Should be closed.

**Comment by Sloy** [comment]
Thanks for the heads up @v1sar, you're right! :)
