### ISSUE TITLE
RecyclerView click actions don't work on wrapped views

### ISSUE THREAD

**Issue by Sloy** [SchibstedSpain/Barista#47]
The method `BaristaRecyclerViewActions.performClick()` only works when the `itemView` of the ViewHolder has the clickListener for the row.
If the clickListener is setted on a children view, the click is not dispatched to it.

For example, when the ItemView contains the clickable row AND a separator/shadow below. Or when using custom Adapters that wrap your view inside another one (like https://github.com/emilsjolander/StickyListHeaders).

The problem seems to be with `clickUsingPerformClick()` method, which calls `performClick()` on the specific `ItemView`, and doesn't let the click pass through its children.

**Comment by rocboronat** [comment]
Fixed with #48 by @Sloy ! ❤️
