### ISSUE TITLE
Same Id matches multiple views in the hierarchy

### ISSUE THREAD

**Issue by despinola** [SchibstedSpain/Barista#49]
Having a view pager with multiple fragments, we are not able to click on one of the items because they have both the same id. 
When trying to get the item by id `ViewMatchers.withId(R.id.offer_list_recyclerview)` we get the following exception from espresso:
android.support.test.espresso.AmbiguousViewMatcherException:

The solution that we found is:
```
    sleep(1000);
    Espresso.onView(allOf(ViewMatchers.withId(R.id.offer_list_recyclerview), isDisplayed())).perform(new ViewAction[] {
        RecyclerViewActions.actionOnItemAtPosition(0, PerformClickAction
            .clickUsingPerformClick())
    });
```

With the isDisplayed() we filter the views to match only the ones that are on the screen, so other fragments doesnt influence. 
Since we are doing a swipe just before clicking, we need to wait until the swipe finish so there is only one visibile (thats why we put the sleep)

Enjoy.

**Comment by rocboronat** [comment]
Thanks @despinola !

**Comment by rocboronat** [comment]
Fix'd!

**Comment by gilbertparreno** [comment]
It worked. Thanks!

**Comment by rocboronat** [comment]
@gilbertparreno just to know, I understand you were having this using while using the last version of Barista?
