### ISSUE TITLE
Avoid asking for an ID if there is only one ListView

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#57]

**Comment by Sloy** [comment]
We should provide both methods. The current implementation of `BaristaListViewActions` is not that great. 

Brace yourselves, refactor is coming.

**Comment by Sloy** [comment]
Should we also merge ListView methods with RecyclerView methods?
It sounds like something Barista would do.

**Comment by Sloy** [comment]
This is being done in https://github.com/SchibstedSpain/Barista/pull/146
