### ISSUE TITLE
click(id) doesn't work when multiple views in the hierarchy

### ISSUE THREAD

**Issue by MarinaTov** [SchibstedSpain/Barista#68]
When I click `close_button`:

![1495025046092](https://cloud.githubusercontent.com/assets/28757304/26154905/2dcbfe50-3ac6-11e7-88d0-3ebe666163a4.jpg)

I get error `android.support.test.espresso.AmbiguousViewMatcherException: 'with id: com.schibsted.android.rocket.kufar.debug:id/close_button' matches multiple views in the hierarchy.
Problem views are marked with '****MATCHES****' below.`

![screen shot 2017-05-17 at 5 38 45 am](https://cloud.githubusercontent.com/assets/28757304/26154912/360b6998-3ac6-11e7-9908-b3abf5831516.png)

**Comment by rocboronat** [comment]
Hi @MarinaTov !

It seems that Espresso is trying to express the idea that multiple Views has the ID you're trying to click. So, it doesn't know what View is the View you want to click.

To fix the issue, we have different options there:
- Give different names to that different buttons. It's the simpler solution, and IMHO, something that improves the maintainability of the whole project. But it could be an issue if it's placed inside a RecyclerView, like your case.
- Use `BaristaRecyclerViewActions.clickRecyclerViewItemChild(R.id.user_preference_category_recycler_view, 0, R.id.close_button)`, that will try to tap `R.id.close_button` of the first child inside `R.id.user_preference_category_recycler_view`.
- Update Barista to the last version (1.0.1), as it only clicks on visible items. It could be an easy fix to this scenario. But the issue will appear again when you place two childs inside the recycler with the `R.id.close_button` visible.

Let me keep this question open to track if the answer helps you fixing it! :·)

**Comment by MarinaTov** [comment]
version 1.0.1 resolved problem
Thanks a lot

**Comment by rocboronat** [comment]
You're welcome! :·)

**Comment by RajaniAchrya** [comment]
Hi, I'm getting id/phoneEditText' matches multiple views in the hierarchy. Problem views are marked with '****MATCHES****' below.
where there's only one view with this id.

**Comment by ShaxGOD** [comment]
How can we just interact with id ? like id/phoneEditText[0] - is that possible ?
