### ISSUE TITLE
Click on a OverFlow hidden Menu

### ISSUE THREAD

**Issue by alorma** [SchibstedSpain/Barista#72]
In order to click on a Menu that is hidden by a Overflow i need to do:

```java
        onView(withClassName(endsWith("OverflowMenuButton"))).perform(ViewActions.click());
        click(R.id.profile_logout_action);
```

It would be great to have a simple `click(R.id.profile_logout_action)`or  maybe better: `clickMenu(R.id.profile_logout_action)`

**Comment by rocboronat** [comment]
Nice! 👍

**Comment by alorma** [comment]
Found:

`openActionBarOverflowOrOptionsMenu(getInstrumentation().getTargetContext());`

**Comment by tim4dev** [comment]
```
 // clickMenu(R.id.xxx); // Does not work if there is a "Menu" button

 // Open the overflow menu OR open the options menu,
 // depending on if the device has a hardware or software overflow menu button.
 openActionBarOverflowOrOptionsMenu(getInstrumentation().getTargetContext());
 // Click the item.
 onView(withText(R.string.text))
    .perform(click());
```

**Comment by rocboronat** [comment]
@tim4dev I don't understand your comment... may you add some clarification about what a "Menu" button means? By the way, it would be great if you open a new issue instead of reusing this closed one.
