### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by kamontat** [SchibstedSpain/Barista#74]
```Java
@Test
public void validateInputText() {
	PermissionGranter.allowPermissionsIfNeeded(Manifest.permission.WRITE_EXTERNAL_STORAGE);
	onView(withId(R.id.fragment_input_id_number)).perform(typeText(SIMPLE_INT)).check(matches(withText(SIMPLE_INT)));
}
```

# description

I setting app to request permission first the first time running, I saw the dialog is out, But this code didn't click allow, and I cause `NoActivityResumedException` 

# Image

![screen shot 2560-05-21 at 2 25 38 pm](https://cloud.githubusercontent.com/assets/14089557/26281997/c9e55412-3e31-11e7-9abf-0888f50b02eb.png)

**Comment by kamontat** [comment]
OK, I already fixed it. 

I change method `allowPermissionsIfNeeded` to...
```Java
public static void allowPermissionsIfNeeded(String permissionNeeded) {
	try {
		if (Build.VERSION.SDK_INT >= 23 && !hasNeededPermission(InstrumentationRegistry.getTargetContext(), permissionNeeded)) {
			UiDevice e = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());
			UiObject allowPermissions = e.findObject((new UiSelector()).clickable(true).checkable(false).index(1));
			if (allowPermissions.exists()) {
				allowPermissions.click();
			}
			e.wakeUp();
		}
	} catch (UiObjectNotFoundException var3) {
		Log.e("Barista", "There is no permissions dialog to interact with", var3);
	} catch (RemoteException e) {
		Log.e("Barista", "Remote error", e);
	}
}
```
I add `e.wakeUp()` and remove `Sleep(long)`

**Comment by rocboronat** [comment]
Hi @kamontat ! Can you send a PR, please? It will be great to know that you authored that change :·)

And one question, what device are you using to run the tests? Which API level?

Thanks a lot!

**Comment by rocboronat** [comment]
Note for the future: probably related with #61

**Comment by kamontat** [comment]
I test on pixel with Android 25 and also on Nexus5 Android 22 too

**Comment by kamontat** [comment]
I have seen that error came because of sleep method

**Comment by rocboronat** [comment]
Ok! And what about `e.wakeUp();`? It's really needed?

**Comment by rocboronat** [comment]
Hey @kamontat , does Barista 1.5.1 fix this issue? If yes, please close the issue :·) Thanks!

**Comment by kamontat** [comment]
@rocboronat sorry, but I use this library for this method only so I just copy the method. I didn't use whole library

**Comment by rocboronat** [comment]
Ok! Then, thanks for the feedback! It moved us to fix the issue. Hope you use more Barista features on the future! :·P

BTW, check `BaristaRule`. Is not the common part of Barista, but it really helps with Flaky tests that crash of Device Farms at random times :·)
