### ISSUE TITLE
Assert No Duplicate Menu

### ISSUE THREAD

**Issue by alorma** [SchibstedSpain/Barista#76]
Hi.

I had a situation today where some menu options were duplicated after refreshing view (tl&dr; using swipe to refresh)

Is there any way to use Barista to check this case? (That view is not duplicate)

**Comment by rocboronat** [comment]
Hi @alorma ! Thanks for the issue!

Right now, there's no way to assert it using Barista. But you can do it with plain Espresso, just trying to match that view by ID or text. If it's duplicated, Espresso with launch a `AmbiguousViewMatcherException`.

**Comment by rocboronat** [comment]
@alorma does my comment answer your question? If yes, please close the issue. Thanks!

**Comment by alorma** [comment]
Hi @rocboronat , thanks, yes it helped. I'm gonna close it

**Comment by rocboronat** [comment]
Thanks! 💋
