### ISSUE TITLE
Fix overflow menu item click tests

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#84]
They were added at #78 , and ignored at CI at #83 

@alorma please, can you try to figure what's happening there? @Sloy added some suggestions at #83 . They could be useful...

**Comment by alorma** [comment]
Sure! I will try to reproduce on my local

**Comment by rocboronat** [comment]
Thanks @alorma !

**Comment by rocboronat** [comment]
@alorma how were the tests? :·/

**Comment by alorma** [comment]
Uhm...

I don't see the tests running on travis right now, are them?

**Comment by rocboronat** [comment]
Nope

**Comment by alorma** [comment]
Let's close this issue then.

On local tests run, and we don't have travis, is not easy to reproduce the issue.

Are you agree?

**Comment by rocboronat** [comment]
Nice :)
